<ul class="nav">
    <li class="trangchu"><a href="index.php">Trang chủ</a></li>
    <li class="daotao">
        <a href="#">Menu và Thể Loại</a>
        <ul>

            <li>
                <a href="?mod=quanlitin">Cập nhật Tin</a>
            </li>
            <li>
                <a href="?mod=addTin">Thêm Tin</a>
            </li>
			<li>
                <a href="?mod=quanliMenu">Cập nhật Menu Chính</a>
            </li>
			<li>
                <a href="?mod=addMenu">Thêm Menu Chính</a>
            </li>
			<li>
                <a href="?mod=quanliTL">Cập nhật Thể Loại</a>
            </li>
            <li>
                <a href="?mod=addTL">Thêm Thể loại</a>
            </li>
        </ul>
    </li>
    <li class="gioithieu">
        <a href="#">Giáo Viên</a>
        <ul>

            <li>
                <a href="?mod=quanliGV">Cập nhật Giáo Viên</a>
            </li>
            <li>
                <a href="?mod=addGV">Thêm Giáo Viên</a>
            </li>

        </ul>
    </li>
    <li class="gioithieu">
        <a href="#">Upload</a>
        <ul>
            <li>
                <a href="?mod=upload">Upload tài liệu</a>
            </li> 
            <li>
                <a href="?mod=quanliTailieu">Cập nhật loại tài liệu</a>
            </li> 
            <li>
                <a href="?mod=addTailieu">Thêm loại tài liệu</a>
            </li> 
        </ul>
    </li>
       <li class="gioithieu">
        <a href="#">ADMIN</a>
        <ul>
            <li>
                <a href="?mod=ttCanhan">Thông tin cá nhân</a>
            </li> 
			<li>
                <a href="?mod=quanliAdmin">Cập nhật Tài khoản</a>
            </li> 
            <li>
                <a href="?mod=addAdmin">Thêm Tài Khoản</a>
            </li> 
            
        </ul>
    </li>
	<li class="daotao">
        <a href="#">BLOG GIÁO VIÊN</a>
        <ul>
            <li>
                <a href="?mod=chitietgv">Thông tin cá nhân giáo viên</a>
            </li> 
			<li>
                <a href="?mod=quanliTintucBloggv">Danh sách tin tức của giáo viên</a>
            </li> 
			<li>
                <a href="?mod=addTinBlog">Đăng thông tin trên blog</a>
            </li> 
             <li>
                <a href="?mod=qlymonhoc">Môn học của giáo viên</a>
            </li>
			<li>
                <a href="?mod=addMonhoc">Thêm mới môn học</a>
            </li>
            
        </ul>
    </li>
